### ISSUE TITLE
SelectelAdapter не возвращает mimetype

### ISSUE THREAD

**Issue by realization** [ArgentCrusade/flysystem-selectel#1]
по логике вызова https://github.com/thephpleague/flysystem/blob/e72817b107fa81fed42843f66e1c2e4934b5bbae/src/Filesystem.php#L284, 
в https://github.com/ArgentCrusade/flysystem-selectel/blob/master/src/SelectelAdapter.php#L58
не хватает поля "mimetype"

**Comment by tzurbaev** [comment]
Cпасибо! Исправил в 1.1.2

**Comment by realization** [comment]
оперативно. все работает. thanks!
